include ../Makefile

define HELP

Creates all respective folder resources using terragrunt to `apply-all`

endef
export HELP

up:
	@terragrunt apply-all

plan:
	@terragrunt plan-all

destroy:
	@terragrunt destroy-all